psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
CREATE TABLE IF NOT EXISTS "$POSTGRES_DB_TBL_USER" (
    user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(40) NOT NULL CHECK (email <> ''),
    pass_hash varchar NOT NULL CHECK (pass_hash <> ''),
    refresh_hash varchar,
    expires_at bigint,
    UNIQUE(email)
);
CREATE TABLE IF NOT EXISTS "$POSTGRES_DB_TBL_CATEGORY" (
    category_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40) NOT NULL CHECK (name <> ''),
    code varchar(40) NOT NULL CHECK (code <> ''),
    description varchar,
    UNIQUE(code)
);
CREATE TABLE IF NOT EXISTS "$POSTGRES_DB_TBL_PRODUCT" (
    product_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(150) NOT NULL CHECK (name <> ''),
    description varchar NOT NULL CHECK (description <> ''),
    UNIQUE(name)
);
CREATE TABLE IF NOT EXISTS "$POSTGRES_DB_TBL_PRODUCT_CATEGORY" (
    product_id int NOT NULL,
    category_id int NOT NULL,
    FOREIGN KEY (product_id) REFERENCES "$POSTGRES_DB_TBL_PRODUCT" ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES "$POSTGRES_DB_TBL_CATEGORY" ON UPDATE CASCADE
	CONSTRAINT product_category_id PRIMARY KEY (product_id, category_id)
);
EOSQL